POST http://localhost:9000/notifyme
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "message": "This is a test message."
}

###

GET http://localhost:9000/